In [30]:
# from selenium import webdriver
# from selenium.webdriver.common.keys import Keys
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

In [38]:
url = "http://www.espn.com/nba/salaries/_/year/2019/seasontype/4"
page = requests.get(url)
soup = BeautifulSoup(page.text, "html.parser")

header = soup.find("tr", attrs={"class": "colhead"})
columns = [col.get_text() for col in header.find_all("td")]
columns = columns[1:]

df_salaries = pd.DataFrame(columns=columns)
df_salaries

Empty DataFrame
Columns: [OWS, DWS, Win Shares, WS/48, OBPM, DBPM, BPM, VORP, Wins Above Replacement]
Index: []

In [32]:
for a in range(1, 503, 40):
    
    if a == 1:
        url = "http://www.espn.com/nba/salaries/_/year/2019/seasontype/4"
        page = requests.get(url)
        soup = BeautifulSoup(page.text, "html.parser")
    else:
        url = "http://www.espn.com/nba/salaries/_/year/2019/page/{}/seasontype/4".format(int(a/40)+1)
        page = requests.get(url)
        soup = BeautifulSoup(page.text, "html.parser")

    players = soup.find_all("tr", attrs = {"class":re.compile("row")})
    for player in players:
        stats = []
        i = 0
        for data in player.find_all("td"):
            string = data.get_text()
            if i == 1:
                name = string.split(",")[0]
                stats.append(name)
            elif i == 2:
                team = string
                stats.append(team)
            elif i == 3:
                space = ""
                salary = int(space.join(string[1:].split(",")))
                stats.append(salary)
            i += 1

        temp_df = pd.DataFrame(stats).transpose()
        temp_df.columns = columns

        df_salaries = pd.concat([df_salaries, temp_df], ignore_index=True)

df_salaries

                        NAME                    TEAM    SALARY
0              Stephen Curry   Golden State Warriors  37457154
1                 Chris Paul         Houston Rockets  35654150
2               LeBron James      Los Angeles Lakers  35654150
3          Russell Westbrook   Oklahoma City Thunder  35654150
4              Blake Griffin         Detroit Pistons  32088932
5             Gordon Hayward          Boston Celtics  31214295
6                 Kyle Lowry         Toronto Raptors  31200000
7                Paul George   Oklahoma City Thunder  30560700
8                Mike Conley       Memphis Grizzlies  30521115
9               James Harden         Houston Rockets  30421854
10              Kevin Durant   Golden State Warriors  30000000
11              Paul Millsap          Denver Nuggets  29230769
12                Al Horford          Boston Celtics  28928709
13            Damian Lillard  Portland Trail Blazers  27977689
14             DeMar DeRozan       San Antonio Spurs  27739975
15           Otto Porter Jr.      Washington Wizards  26011913
16              Jrue Holiday    New Orleans Pelicans  25976111
17               CJ McCollum  Portland Trail Blazers  25759766
18               Joel Embiid      Philadelphia 76ers  25467250
19            Andrew Wiggins  Minnesota Timberwolves  25467250
20              Bradley Beal      Washington Wizards  25434263
21             Anthony Davis    New Orleans Pelicans  25434263
22            Andre Drummond         Detroit Pistons  25434263
23          Hassan Whiteside              Miami Heat  25434262
24              Nikola Jokic          Denver Nuggets  24605181
25              Steven Adams   Oklahoma City Thunder  24157303
26     Giannis Antetokounmpo         Milwaukee Bucks  24157303
27                Marc Gasol       Memphis Grizzlies  24119025
28                Kevin Love     Cleveland Cavaliers  24119025
29           Harrison Barnes        Sacramento Kings  24107258
..                       ...                     ...       ...
473             Andrew Bogut   Golden State Warriors    307648
474             Jaylen Adams           Atlanta Hawks    270014
475         Danuel House Jr.         Houston Rockets    247827
476          Jimmer Fredette            Phoenix Suns    208509
477              Tim Frazier         Milwaukee Bucks    196553
478           Dairis Bertans    New Orleans Pelicans    194220
479             Ray Spalding            Phoenix Suns    184746
480            Deonte Burton   Oklahoma City Thunder    151587
481         Cameron Reynolds  Minnesota Timberwolves    108953
482            Chris Chiozza         Houston Rockets     90005
483           JaKarr Sampson           Chicago Bulls     85458
484       Donatas Motiejunas       San Antonio Spurs     59820
485              Greg Monroe         Toronto Raptors     59820
486  Michael Carter-Williams           Orlando Magic     59820
487             Tyler Zeller       Memphis Grizzlies     59820
488           Jemerrio Jones      Los Angeles Lakers     52108
489           Mitchell Creek           Brooklyn Nets     47371
490          Isaac Humphries           Atlanta Hawks     47371
491        Billy Garrett Jr.         New York Knicks     42634
492               BJ Johnson        Sacramento Kings     42634
493            Deyonta Davis           Atlanta Hawks     25367
494          Michael Frazier         Houston Rockets     23685
495              Yante Maten              Miami Heat     18948
496            Eric Moreland         Toronto Raptors     17092
497             Jordan McRae      Washington Wizards     17092
498          Jonathan Gibson          Boston Celtics     17092
499            Tarik Phillip      Washington Wizards      9474
500          Duncan Robinson              Miami Heat      9474
501              Theo Pinson           Brooklyn Nets      4737
502            Kendrick Nunn              Miami Heat      4737

[503 rows x 3 columns]

In [33]:
df_salaries.to_csv(r"/Users/Srikar/Desktop/Sports/Data/salaries18-19.csv", index=False, sep=',', encoding='utf-8')

In [34]:
df_salaries = pd.read_csv("/Users/Srikar/Desktop/Sports/Data/salaries18-19.csv")
final_df = pd.read_csv("/Users/Srikar/Desktop/Sports/Data/stats18-19.csv")

In [35]:
final_df.insert(final_df.shape[1]-1, "SALARY", int(0))
# number of columns is also len(final_df.columns)

In [36]:
for ind in range(final_df.shape[0]):
    for row in range(df_salaries.shape[0]):
        if final_df.loc[ind, "NAME"] == df_salaries.loc[row, "NAME"]:
            final_df.loc[ind, "TEAM"] = df_salaries.loc[row, "TEAM"]
            final_df.loc[ind, "SALARY"] = df_salaries.loc[row, "SALARY"]
            break
final_df.head()

,NAME,TEAM,POS,GP,MIN,PTS,FGM,FGA,FG%,3PM,...,FT%,REB,AST,STL,BLK,TO,DD2,TD3,SALARY,PER
0,James Harden,Houston Rockets,PG,78,36.8,36.1,10.8,24.5,44.2,4.8,...,87.9,6.6,7.5,2.0,0.7,5.0,34,7,30421854,30.62
1,Paul George,Oklahoma City Thunder,SF,77,36.9,28.0,9.2,21.0,43.8,3.8,...,83.9,8.2,4.1,2.2,0.4,2.7,24,1,30560700,23.32
2,Giannis Antetokounmpo,Milwaukee Bucks,PF,72,32.8,27.7,10.0,17.3,57.8,0.7,...,72.9,12.5,5.9,1.3,1.5,3.7,54,5,24157303,30.95
3,Joel Embiid,Philadelphia 76ers,C,64,33.7,27.5,9.1,18.7,48.4,1.2,...,80.4,13.6,3.7,0.7,1.9,3.5,58,2,25467250,26.21
4,Stephen Curry,Golden State Warriors,PG,69,33.8,27.3,9.2,19.4,47.2,5.1,...,91.6,5.3,5.2,1.3,0.4,2.8,3,0,37457154,24.45

In [37]:
final_df.to_csv(r"/Users/Srikar/Desktop/Sports/Data/alldata18-19.csv", index=False, sep=',', encoding='utf-8')